### ISSUE TITLE
threads(n) get rid of that n!

### ISSUE THREAD

**Issue by bykof** [madisonmay/Tomorrow#11]
Hi madison, 
I am very excited of your python module. But can you change the code so that I can use threads() as decorator but not set an n. So the number of threads append dynamicly to the threadpool? 
Thank you very much.

**Comment by aaossa** [comment]
It seems hard because of [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.submit). If you don't set `n` in @madisonmay's  program it raises TypeError, and if you don't set it in `ThreadPoolExecutor` it defaults to 1. I'll keep an eye on this, is a small and powerfull mini-module.

**Comment by madisonmay** [comment]
You can simulate the "number of threads append dynamicly to the threadpool" behavior by using a very high n (it's passed through as the max_workers argument to `ThreadPoolExecutor.__init__()`).  However, I don't think it makes sense to behave this way by default.

**Comment by kcbsbo** [comment]
could async_add = threads(n)(add)  help?

python rookie
