### ISSUE TITLE
Does this support Python3

### ISSUE THREAD

**Issue by kehao95** [madisonmay/Tomorrow#18]
You said 

> Magic decorator syntax for asynchronous code in Python 2.7+

**Comment by madisonmay** [comment]
Ah -- yes I should be more clear there.  Python3 is not supported, because the `tomorrow` library takes advantage of some Python2 specific "features".  I'll update the README to be more explicit.

**Comment by kehao95** [comment]
Thank you

**Comment by madisonmay** [comment]
No problem, thanks for the bug report!

**Comment by killpanda** [comment]
May I know which specific "features" of Python2 are using?

**Comment by madisonmay** [comment]
Of course, sorry it took me so long to get back to you.  I'm making use of the fact that calls to Python magic methods (like `__str__`, `__add__`, etc.) are routed through `__getattr__` when you use old-style Python classes, initialized without a parent class.  This means that I can tell when the value of the future is accessed in any way.  It's a bit terrifying to think about, but seems to work well so I've sort of come to terms with it.

**Comment by killpanda** [comment]
Thanks for your reply. But I am not sure why you defined object like

``` python
class Tomorrow():
    pass
```

instead of 

``` python
class Tomorrow(object):
    pass
```

You can overwrite `__getattr__` in py2 and py3 anyway. Is there any specific reason?

**Comment by madisonmay** [comment]
`__getattr__` behaves differently when you use the second instead of the first.  New style python classes do not have calls to magic methods routed through `__getattr__`, and actually usually are not guaranteed to router through anything but `__getattribute__` (only present in new-style Python classes).  See http://www.rafekettler.com/magicmethods.html#access for details.
